create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data longtext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
create table address (employee_employee_id bigint, id bigint not null, line1 varchar(255), line2 varchar(255), line3 varchar(255), line4 varchar(255), line5 varchar(255), primary key (id)) engine=InnoDB;
create table address_seq (next_val bigint) engine=InnoDB;
insert into address_seq values ( 1 );
create table company (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table company_seq (next_val bigint) engine=InnoDB;
insert into company_seq values ( 1 );
create table document_metadata_seq (next_val bigint) engine=InnoDB;
insert into document_metadata_seq values ( 1 );
create table document_metadata (doc_metadata_id bigint not null, file_name varchar(255), s3uri varchar(255), primary key (doc_metadata_id)) engine=InnoDB;
create table employee (address_id bigint, employee_id bigint not null, name varchar(255), primary key (employee_id)) engine=InnoDB;
create table employee_seq (next_val bigint) engine=InnoDB;
insert into employee_seq values ( 1 );
create table extracted_financial_entities_seq (next_val bigint) engine=InnoDB;
insert into extracted_financial_entities_seq values ( 1 );
create table extracted_financial_entities (company_id bigint not null, extracted_entities_id bigint not null, raw_data tinytext, primary key (extracted_entities_id)) engine=InnoDB;
create table financial_document_seq (next_val bigint) engine=InnoDB;
insert into financial_document_seq values ( 1 );
create table financial_document (company_id bigint not null, document_metadata_doc_metadata_id bigint, risk_docs_id bigint not null, primary key (risk_docs_id)) engine=InnoDB;
alter table address add constraint UK_ba88tqs2eokbqf73qf2he4sg1 unique (employee_employee_id);
alter table employee add constraint UK_qrbsk9ljmhfje93me0n7xwdxq unique (address_id);
alter table financial_document add constraint UK_k0clmj5p40xci8c4bpfxxm2q2 unique (document_metadata_doc_metadata_id);
alter table address add constraint FKq5bhavjqmjp3cppli0lj1cy00 foreign key (employee_employee_id) references employee (employee_id);
alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
alter table extracted_financial_entities add constraint FK8wpaf77ms4uqksgs7kwc5k6a5 foreign key (company_id) references company (id);
alter table financial_document add constraint FKtindt8njti39vo7ss9ujed79f foreign key (company_id) references company (id);
alter table financial_document add constraint FKlwngbvilllwo0psq5fh2fcyua foreign key (document_metadata_doc_metadata_id) references document_metadata (doc_metadata_id);
